basePath: /v1
definitions:
  models.CreateAllStudentRequest:
    properties:
      email:
        items:
          type: string
        type: array
      first_name:
        items:
          type: string
        maxItems: 30
        minItems: 2
        type: array
      last_name:
        items:
          type: string
        maxItems: 30
        minItems: 2
        type: array
      phone_number:
        items:
          type: string
        type: array
      username:
        items:
          type: string
        maxItems: 30
        minItems: 2
        type: array
    required:
    - email
    - first_name
    - last_name
    - username
    type: object
  models.CreateStudent:
    properties:
      student:
        items:
          $ref: '#/definitions/models.CreateAllStudentRequest'
        type: array
    required:
    - student
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.GetAllStudentsResponse:
    properties:
      categories:
        items:
          $ref: '#/definitions/models.Student'
        type: array
      count:
        type: integer
    type: object
  models.ResponseOK:
    properties:
      message:
        type: string
    type: object
  models.Student:
    properties:
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      phone_number:
        type: string
      username:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  title: Swagger for blog api
  version: "1.0"
paths:
  /student:
    get:
      consumes:
      - application/json
      description: Get students
      parameters:
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Page
        in: query
        name: page
        required: true
        type: integer
      - description: Search
        in: query
        name: sezrch
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetAllStudentsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get students
      tags:
      - student
    post:
      consumes:
      - application/json
      description: Create a student
      parameters:
      - description: Student
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/models.CreateStudent'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ResponseOK'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create a student
      tags:
      - student
swagger: "2.0"
